<?php
// source: /srv/teslacam.online/info.phlo
// phlo:   1.0β
class info extends obj {
	public static function BothGETInfo(){
		return view(phlo('info'), 'Info', scroll: 0);
	}
	protected function view():string {
		$phloView = [];
		$phloView[] = "<div id=\"welcome\" class=\"welcome\">";
		$phloView[] = "\t<div class=\"wc\">";
		$phloView[] = "\t\t<div class=\"topbar\">";
		$phloView[] = "\t\t\t<a class=\"async\" href=\"/\">Home</a>";
		$phloView[] = "\t\t\t<a class=\"btn\" href=\"/viewer\" target=\"_blank\">Open Viewer</a>";
		$phloView[] = "\t\t</div>";
		$phloView[] = "\t\t<h1>TeslaCam Viewer</h1>";
		$phloView[] = "\t\t<p>This page explains what the TeslaCam Viewer is, how to use it, and answers common questions about privacy, offline use, and donations.</p>";
		$phloView[] = "\t\t<hr>";
		$phloView[] = "\t\t<h2 id=\"overview\">Overview</h2>";
		$phloView[] = "\t\t<p>TeslaCam Viewer is a single-page, standalone web app that lets you browse and play your Tesla dashcam footage directly in your browser. It supports multi-camera playback, timelines, a quick filter bar, location markers on a mini-map, and smooth switching between clips.</p>";
		$phloView[] = "\t\t<ul>";
		$phloView[] = "\t\t\t<li><strong>Zero uploads:</strong> your files never leave your device.</li>";
		$phloView[] = "\t\t\t<li><strong>No install required:</strong> just open the HTML file in a modern browser.</li>";
		$phloView[] = "\t\t\t<li><strong>Works offline:</strong> you can save the page and use it without internet access.</li>";
		$phloView[] = "\t\t\t<li><strong>Donationware:</strong> free to use; consider supporting via <a href=\"https://www.paypal.me/jordiboerman\" target=\"_blank\" rel=\"noopener\">PayPal</a>, <a href=\"https://ko-fi.com/jordiboerman\" target=\"_blank\" rel=\"noopener\">Ko-fi</a>, or <a href=\"https://www.buymeacoffee.com/jordiboerman\" target=\"_blank\" rel=\"noopener\">Buy Me a Coffee</a>.</li>";
		$phloView[] = "\t\t</ul>";
		$phloView[] = "\t\t<hr>";
		$phloView[] = "\t\t<h2 id=\"privacy\">Privacy &amp; Security</h2>";
		$phloView[] = "\t\t<p><strong>Nothing is sent to any server.</strong> The Viewer runs fully client-side in your browser.</p>";
		$phloView[] = "\t\t<ul>";
		$phloView[] = "\t\t\t<li>does not upload or sync files;</li>";
		$phloView[] = "\t\t\t<li>does not use analytics or tracking pixels;</li>";
		$phloView[] = "\t\t\t<li>does not store your videos beyond the current session (object URLs live only in memory).</li>";
		$phloView[] = "\t\t</ul>";
		$phloView[] = "\t\t<p>When you select your TeslaCam folder, the browser grants the page read-only access to those files for the current session only.</p>";
		$phloView[] = "\t\t<p><strong>Map note:</strong> when you open the map, it loads tile images from OpenStreetMap; your video files are never uploaded.</p>";
		$phloView[] = "\t\t<p>If you refresh or close the page, access to your files is revoked by the browser and must be granted again next time.</p>";
		$phloView[] = "\t\t<hr>";
		$phloView[] = "\t\t<h2 id=\"saving\">Using it offline (optional)</h2>";
		$phloView[] = "\t\t<p>";
		$phloView[] = "\t\t\tTeslaCam Viewer is designed to work primarily as a website. This helps keep the project visible, up to date, and easy to support.";
		$phloView[] = "\t\t\tHowever, offline use is available if you prefer.";
		$phloView[] = "\t\t</p>";
		$phloView[] = "\t\t<p>";
		$phloView[] = "\t\t\t<strong>Option 1: Save as a single HTML file</strong><br>";
		$phloView[] = "\t\t\tYou can <a href=\"/download\">download</a> once and save the HTML file locally.";
		$phloView[] = "\t\t\tOpening this file directly in your browser gives you the full viewer experience, fully offline.";
		$phloView[] = "\t\t</p>";
		$phloView[] = "\t\t<p>";
		$phloView[] = "\t\t\t<strong>Option 2: Install as a PWA (recommended for convenience)</strong><br>";
		$phloView[] = "\t\t\tMost modern browsers allow you to install TeslaCam Viewer as a Progressive Web App.";
		$phloView[] = "\t\t\tUse the \"Install app\" option in your browser menu while visiting the site.";
		$phloView[] = "\t\t\tThis adds the viewer to your device like a native app, with faster access and optional offline availability.";
		$phloView[] = "\t\t</p>";
		$phloView[] = "\t\t<p class=\"subtle\">";
		$phloView[] = "\t\t\tTip: Even when installed, visiting the website occasionally ensures you're always using the latest version and helps support ongoing development.";
		$phloView[] = "\t\t</p>";
		$phloView[] = "\t\t<hr>";
		$phloView[] = "\t\t<h2 id=\"folders\">Required TeslaCam folders</h2>";
		$phloView[] = "\t\t<p>Select your TeslaCam root directory. The app expects these standard subfolders:</p>";
		$phloView[] = "\t\t<ul>";
		$phloView[] = "\t\t\t<li><strong>RecentClips/</strong></li>";
		$phloView[] = "\t\t\t<li><strong>SavedClips/</strong></li>";
		$phloView[] = "\t\t\t<li><strong>SentryClips/</strong></li>";
		$phloView[] = "\t\t</ul>";
		$phloView[] = "\t\t<p>If these folders are missing or empty, the app will show an error or an empty list. Each <em>event</em> is presented as a set of clips that can include multiple cameras (front, left repeater, right repeater, back). All <strong>RecentClips</strong> in the selected folder are presented as one continuous event for browsing convenience.</p>";
		$phloView[] = "\t\t<hr>";
		$phloView[] = "\t\t<h2 id=\"howto\">How to use</h2>";
		$phloView[] = "\t\t<ol>";
		$phloView[] = "\t\t\t<li>Click <strong>Open folder</strong> and pick your TeslaCam root folder.</li>";
		$phloView[] = "\t\t\t<li>Use the left sidebar to browse events. Click an event to load it.</li>";
		$phloView[] = "\t\t\t<li>Use the <strong>Play</strong> button and the timeline scrubber to control playback.</li>";
		$phloView[] = "\t\t\t<li>Switch layouts by clicking a camera view (single vs quad). On narrow screens, the focused camera is on top and the others appear as small previews below.</li>";
		$phloView[] = "\t\t\t<li>Open the <strong>Map</strong> to see approximate locations for events. Click a marker to jump to that event.</li>";
		$phloView[] = "\t\t\t<li>Use the filter bar for <strong>Sentry / Recent / Saved</strong> sources and sorting.</li>";
		$phloView[] = "\t\t\t<li>Adjust <strong>Speed, Brightness, Contrast</strong> in the settings panel.</li>";
		$phloView[] = "\t\t</ol>";
		$phloView[] = "\t\t<hr>";
		$phloView[] = "\t\t<h2 id=\"features\">Key features</h2>";
		$phloView[] = "\t\t<ul>";
		$phloView[] = "\t\t\t<li><strong>Multi-camera sync:</strong> the Viewer lines up the front/left/right/back clips on a single timeline.</li>";
		$phloView[] = "\t\t\t<li><strong>Smooth segment transitions:</strong> segments are preloaded to avoid stutter at boundaries.</li>";
		$phloView[] = "\t\t\t<li><strong>Global scrubber:</strong> one slider targets all cameras; the app selects the right segment automatically.</li>";
		$phloView[] = "\t\t\t<li><strong>Map integration:</strong> optional markers based on event metadata (if available).</li>";
		$phloView[] = "\t\t\t<li><strong>Responsive layout:</strong> optimized for narrow and wide screens.</li>";
		$phloView[] = "\t\t</ul>";
		$phloView[] = "\t\t<hr>";
		$phloView[] = "\t\t<h2 id=\"supports\">What it supports</h2>";
		$phloView[] = "\t\t<h3>Sentry Mode Viewer</h3>";
		$phloView[] = "\t\t<p>Browse Sentry events with thumbnails (when available), timestamps, and optional event metadata like reason and approximate location.</p>";
		$phloView[] = "\t\t<h3>RecentClips Viewer</h3>";
		$phloView[] = "\t\t<p>RecentClips are presented as one continuous stream for fast browsing and scrubbing without juggling separate segments.</p>";
		$phloView[] = "\t\t<h3>SavedClips Viewer</h3>";
		$phloView[] = "\t\t<p>View Saved clips the same way as Sentry, with quick filtering and synced camera layout.</p>";
		$phloView[] = "\t\t<h3>Multi-camera dashcam playback</h3>";
		$phloView[] = "\t\t<p>Front/left/right/back clips are aligned on one timeline. Use a single scrubber to jump through the event across all cameras.</p>";
		$phloView[] = "\t\t<hr>";
		$phloView[] = "\t\t<h2 id=\"shortcuts\">Keyboard shortcuts</h2>";
		$phloView[] = "\t\t<ul>";
		$phloView[] = "\t\t\t<li><strong>Space</strong> Play/Pause</li>";
		$phloView[] = "\t\t\t<li><strong>Left/right</strong> Forward/backward</li>";
		$phloView[] = "\t\t</ul>";
		$phloView[] = "\t\t<hr>";
		$phloView[] = "\t\t<h2 id=\"donate\">Donationware</h2>";
		$phloView[] = "\t\t<p>The app is free to use. If it saves you time or proves helpful, please consider supporting the project. Thank you!</p>";
		$phloView[] = "\t\t".indentView(phlo('app')->support , 2)."";
		$phloView[] = "\t\t<hr>";
		$phloView[] = "\t\t<h2 id=\"troubleshooting\">Troubleshooting checklist</h2>";
		$phloView[] = "\t\t<ul>";
		$phloView[] = "\t\t\t<li>Reload the page and reselect the TeslaCam folder.</li>";
		$phloView[] = "\t\t\t<li>Confirm the folder contains <strong>RecentClips</strong>, <strong>SavedClips</strong>, and <strong>SentryClips</strong>.</li>";
		$phloView[] = "\t\t\t<li>Try a different browser if playback or file permissions misbehave.</li>";
		$phloView[] = "\t\t\t<li>Move the clips to a faster disk if you notice I/O bottlenecks.</li>";
		$phloView[] = "\t\t</ul>";
		$phloView[] = "\t\t<hr>";
		$phloView[] = "\t\t<h2 id=\"credits\">Credits</h2>";
		$phloView[] = "\t\t<p>Tesla is a trademark of Tesla, Inc. This project is an independent Viewer designed for personal use with locally stored footage.</p>";
		$phloView[] = "\t\t<hr>";
		$phloView[] = "\t\t".indentView(phlo('app')->qai , 2)."";
		$phloView[] = "\t\t<div>";
		$phloView[] = "\t\t\t<p>Other products in our ecosystem:</p>";
		$phloView[] = "\t\t\t<ul class=\"qai-list\">";
		$phloView[] = "\t\t\t\t<li>";
		$phloView[] = "\t\t\t\t\t<a href=\"https://ecms.nu/\" target=\"_blank\"><strong>eCMS</strong></a> a lightweight encrypted content management system for structured, maintainable data.";
		$phloView[] = "\t\t\t\t</li>";
		$phloView[] = "\t\t\t\t<li>";
		$phloView[] = "\t\t\t\t\t<a href=\"https://filesystem.online/\" target=\"_blank\"><strong>Filesystem.online</strong></a> a smart, local-first tool that organizes files by creating the right folders automatically, based on what the files actually contain.";
		$phloView[] = "\t\t\t\t</li>";
		$phloView[] = "\t\t\t</ul>";
		$phloView[] = "\t\t</div>";
		$phloView[] = "\t</div>";
		$phloView[] = "</div>";
		return implode(lf, $phloView);
	}
}
